[package]
name = "wgan"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.20.1", features = ["train", "autodiff", "dataset", "cuda"] }   
burn-store = "0.20.1"
image = { version = "0.25.9", features = ["png"] }
rand = "0.10.0"

[build-dependencies]
burn-import = { version = "0.20.1", default-features = false, features = ["onnx"] }
